//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/prctl.h>
#include <sys/wait.h>
#include <unistd.h>

// ------------------------ Functions -------------------------

// Address range: 0x80486c8 - 0x8048826
int main(int argc, char ** argv) {
    int32_t pid = fork(); // 0x80486d6
    int32_t str; // bp-160
    __asm_rep_stosd_memset((char *)&str, 0, 32);
    int32_t stat_loc = 0; // bp-164
    if (pid != 0) {
        // 0x8048769
        // branch -> 0x8048769
        while (true) {
            // 0x8048769
            wait((int32_t)&stat_loc);
            uint32_t v1 = stat_loc % 128; // 0x8048787
            if (v1 != 0) {
                // 0x804878e
                if ((char)(v1 + 1) < 2) {
                    // 0x80487ba
                    if (ptrace(3) == 11) {
                        // break -> 0x80487f6
                        break;
                    }
                    // continue -> 0x8048769
                    continue;
                }
            }
            // 0x80487ac
            puts("child is exiting...");
            // branch -> 0x804881a
            // 0x804881a
            return 0;
        }
        // 0x80487f6
        puts("no exec() for you");
        kill(pid, SIGKILL);
        // branch -> 0x804881a
    } else {
        // 0x8048713
        int32_t v2;
        int32_t v3;
        int32_t * v4;
        prctl(PR_SET_PDEATHSIG, 1, v2, v3, (int32_t)&v4);
        ptrace(0);
        puts("Give me some shellcode, k");
        gets((char *)&str);
        // branch -> 0x804881a
    }
    // 0x804881a
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// __pid_t fork(void);
// char * gets(char * s);
// int kill(__pid_t pid, int sig);
// int prctl(int option, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5);
// long int ptrace(enum __ptracerequest __request, ...);
// int puts(const char * s);
// __pid_t wait(__WAIT_STATUS stat_loc);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected functions: 1
// Decompilation date: 2018-08-20 15:42:51
