//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// ------------------- Function Prototypes --------------------

int32_t decrypt(int32_t a1);
int32_t test(void);

// --------------------- Global Variables ---------------------

bool g1 = false; // df
int32_t g2 = 0; // esp

// ------------------------ Functions -------------------------

// Address range: 0x8048660 - 0x8048747
int32_t decrypt(int32_t a1) {
    int32_t v1 = *(int32_t *)20; // 0x8048668
    int32_t v2 = 0x757c7d51; // bp-33
    int32_t v3 = &v2; // 0x804869c
    int32_t v4 = v3; // 0x80486b2
    int32_t v5 = -1; // 0x80486b2
    // branch -> bb
    while (true) {
        // bb
        if (v5 != 0) {
            // bb38
            if (*(char *)v4 == 0) {
                // break -> bb39
                break;
            }
            v4 += (g1 ? -1 : 1);
            v5--;
            // continue -> bb
            continue;
        }
        int32_t v6 = -2; // 0x80486b8
        char * str = NULL;
        if (v6 != 0) {
            int32_t v7 = 0; // 0x80486e59
            char * v8 = (char *)(v7 + v3); // 0x80486cd
            *v8 = (char)((int32_t)*v8 ^ a1);
            while (v7 + 1 != v6) {
                // 0x80486c7
                v7++;
                v8 = (char *)(v7 + v3);
                *v8 = (char)((int32_t)*v8 ^ a1);
                // continue -> 0x80486c7
            }
            // 0x80486ed
            str = (char *)v6;
            // branch -> 0x80486ed
        }
        int32_t v9 = g1 ? -1 : 1; // 0x8048700
        bool v10 = false; // 0x804870216
        int32_t v11 = (int32_t)"Congratulations!"; // 0x8048700
        int32_t v12 = v3; // 0x8048700
        int32_t v13 = 17; // 0x8048700
        // branch -> bb40
        int32_t puts_rc;
        bool v14; // 0x8048705
        int32_t result; // 0x8048746
        int32_t * v15; // 0x8048723
        int32_t * v16;
        while (true) {
            // bb40
            v14 = v10;
            if (v13 != 0) {
                unsigned char v17 = *(char *)v12; // 0x8048700
                unsigned char v18 = *(char *)v11; // 0x8048700
                if (v17 != v18) {
                    v14 = v17 < v18;
                    // break -> bb42
                    break;
                }
                v10 = v17 < v18;
                v11 += v9;
                v12 += v9;
                v13--;
                // continue -> bb40
                continue;
            }
            // bb42
            v15 = (int32_t *)g2;
            if ((((int32_t)!((true | v14)) - (int32_t)v14) % 256 || v3 & -256) != 0) {
                // 0x8048723
                *v15 = (int32_t)"\nInvalid Password";
                puts_rc = puts(str);
                // branch -> 0x804872f
            } else {
                // 0x8048715
                *v15 = (int32_t)"/bin/sh";
                puts_rc = system(str);
                // branch -> 0x804872f
            }
            // 0x804872f
            if (*(int32_t *)20 != v1) {
                // 0x804873b
                __stack_chk_fail();
                result = (int32_t)&v16;
                // branch -> 0x8048740
            } else {
                result = puts_rc;
            }
            // 0x8048740
            return result;
        }
        // bb42
        v15 = (int32_t *)g2;
        if ((((int32_t)!((false | v14)) - (int32_t)v14) % 256 || v3 & -256) != 0) {
            // 0x8048723
            *v15 = (int32_t)"\nInvalid Password";
            puts_rc = puts(str);
            // branch -> 0x804872f
        } else {
            // 0x8048715
            *v15 = (int32_t)"/bin/sh";
            puts_rc = system(str);
            // branch -> 0x804872f
        }
        // 0x804872f
        if (*(int32_t *)20 != v1) {
            // 0x804873b
            __stack_chk_fail();
            result = (int32_t)&v16;
            // branch -> 0x8048740
        } else {
            result = puts_rc;
        }
        // 0x8048740
        return result;
    }
}

// Address range: 0x8048747 - 0x804885a
int32_t test(void) {
    // 0x8048747
    int32_t v1;
    int32_t v2;
    int32_t v3 = v1 - v2; // 0x8048755                              => 322424845 - NOTRE MOT DE PASSE  (322424827)
    int32_t result; // 0x8048859
    switch (v3) {
        default: {
            // 0x804884a
            result = decrypt(rand());
            // branch -> 0x8048858
            break;
        }
        case 1: {
            // 0x8048775
            result = decrypt(1);
            // branch -> 0x8048858
            break;
        }
        case 2: {
            // 0x8048785
            result = decrypt(2);
            // branch -> 0x8048858
            break;
        }
        case 3: {
            // 0x8048795
            result = decrypt(3);
            // branch -> 0x8048858
            break;
        }
        case 4: {
            // 0x80487a5
            result = decrypt(4);
            // branch -> 0x8048858
            break;
        }
        case 5: {
            // 0x80487b5
            result = decrypt(5);
            // branch -> 0x8048858
            break;
        }
        case 6: {
            // 0x80487c5
            result = decrypt(6);
            // branch -> 0x8048858
            break;
        }
        case 7: {
            // 0x80487d5
            result = decrypt(7);
            // branch -> 0x8048858
            break;
        }
        case 8: {
            // 0x80487e2
            result = decrypt(8);
            // branch -> 0x8048858
            break;
        }
        case 9: {
            // 0x80487ef
            result = decrypt(9);
            // branch -> 0x8048858
            break;
        }
        case 16: {
            // 0x80487fc
            result = decrypt(16);
            // branch -> 0x8048858
            break;
        }
        case 17: {
            // 0x8048809
            result = decrypt(17);
            // branch -> 0x8048858
            break;
        }
        case 18: {
            // 0x8048816
            result = decrypt(18);
            // branch -> 0x8048858
            break;
        }
        case 19: {
            // 0x8048823
            result = decrypt(19);
            // branch -> 0x8048858
            break;
        }
        case 20: {
            // 0x8048830
            result = decrypt(20);
            // branch -> 0x8048858
            break;
        }
        case 21: {
            // 0x804883d
            result = decrypt(21);
            // branch -> 0x8048858
            break;
        }
    }
    // 0x8048858
    return result;
}

// Address range: 0x804885a - 0x80488e1
int main(int argc, char ** argv) {
    char * t = (char *)0; // bp-52
    *(int32_t *)((int32_t)&t + 4) = 0;
    *(int32_t *)g2 = time((int32_t *)t);
    srand((int32_t)t);
    *(int32_t *)g2 = (int32_t)"***********************************";
    puts(t);
    *(int32_t *)g2 = (int32_t)"*\t\tlevel03\t\t**";
    puts(t);
    *(int32_t *)g2 = (int32_t)"***********************************";
    puts(t);
    *(int32_t *)g2 = (int32_t)"Password:";
    int32_t * format;
    printf((char *)&format);
    *(int32_t *)(g2 + 4) = g2 + 28;
    *(int32_t *)g2 = (int32_t)"%d";
    scanf((char *)&format);
    *(int32_t *)(g2 + 4) = 0x1337d00d;
    *(int32_t *)g2 = *(int32_t *)(g2 + 28);
    test();
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// void __stack_chk_fail(void);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// int rand(void);
// int scanf(const char * restrict format, ...);
// void srand(unsigned int seed);
// int system(const char * command);
// time_t time(time_t * timer);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected functions: 3
// Decompilation date: 2018-08-20 14:46:33
